"""Append personal_qa_hallucination instances to existing test.json files.

Additive alternative to a full `scripts/prepare_eval_data.py` rebuild: builds
ONLY the new hallucination/abstention probes (discovery-LLM-gated) and merges
them into each persona's existing `backend/{uid}/test.json`, leaving every
existing row untouched. A full rebuild would re-spend hundreds of LLM calls
per user and churn all existing instances; this spends ~6-9 discovery calls
per user (one per instance + validation retries).

Idempotent: a user whose test.json already carries personal_qa_hallucination
rows is skipped unless --force (which drops those rows and regenerates).

Usage:
    # Dry run — corpus scan + absence-verified domains only, NO LLM calls:
    python scripts/add_personal_qa_hallucination.py --all --dry_run

    # Generate + append for one user / all users (LLM calls — ask first!):
    python scripts/add_personal_qa_hallucination.py --user_id 115
    python scripts/add_personal_qa_hallucination.py --all

NOTE: persona.html is NOT regenerated by this script (it renders from the
full in-memory row list that only a full prepare run holds). The test cards
for the new task appear on the next `prepare_eval_data.py` run.

Resume/replay safety (AUDIT.md failure mode 17): existing rows keep their
stored `query_id` VERBATIM — this script never renumbers (only a full
prepare rebuild does), so a later `--resume` of an existing results dir
re-runs ONLY the new pqa rows. Two caveats remain: (a) do not run this
while any results dir for a persona is actively mid-resume/replay, and
(b) `--replay_from` an older run against the appended test.json has no
saved responses for the new rows — they replay as "" and score 0
(`non_substantive_response=1`); exclude the new task_type when comparing
replayed configs built before the append.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "scripts"))

TASK_TYPE = "personal_qa_hallucination"


def _users_with_test_json(backend_dir: Path) -> list[str]:
    return sorted(
        (p.parent.name for p in backend_dir.glob("*/test.json")),
        key=lambda s: (len(s), s),
    )


def _existing_task_rows(records: list[dict]) -> list[int]:
    return [i for i, r in enumerate(records)
            if isinstance(r, dict) and r.get("task_type") == TASK_TYPE]


def _atomic_write_json(path: Path, records: list[dict]) -> None:
    """json.dump to a temp file in the same directory, then os.replace —
    matches dump_test_samples_json's serialization (indent=2, no ASCII
    escaping) so the file format stays uniform."""
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp",
                               dir=str(path.parent))
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(records, f, indent=2, ensure_ascii=False)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def _dry_run_one(backend_dir: Path, uid: str) -> dict:
    """Absence scan only — which fact domains survive for this user."""
    from evaluation.tasks.personal_qa_hallucination import (
        FACT_DOMAINS, build_visible_corpus, domain_term_hits,
    )
    corpus, n_events = build_visible_corpus(backend_dir, uid)
    absent, disqualified = [], {}
    for key, d in FACT_DOMAINS.items():
        hits = domain_term_hits(corpus, d["search_terms"])
        if hits:
            disqualified[key] = hits[:3]
        else:
            absent.append(key)
    return {"user_id": uid, "n_events": n_events,
            "absent_domains": absent, "disqualified": disqualified}


def _append_one(
    backend_dir: Path,
    uid: str,
    discovery_llm,
    rng_seed: int,
    force: bool,
    verbose: bool = True,
) -> dict:
    from evaluation.backend_query import BackendQuery
    from evaluation.tasks.personal_qa_hallucination import (
        build_personal_qa_hallucination,
    )
    from data_preparation.visualize import dump_test_samples_json
    import prepare_eval_data as _prep

    test_path = backend_dir / uid / "test.json"
    records = json.loads(test_path.read_text(encoding="utf-8"))
    if not isinstance(records, list):
        return {"user_id": uid, "status": "error",
                "error": f"{test_path} is not a JSON list"}

    existing_idx = _existing_task_rows(records)
    if existing_idx and not force:
        return {"user_id": uid, "status": "skipped_exists",
                "n_existing": len(existing_idx)}
    if existing_idx and force:
        records = [r for i, r in enumerate(records) if i not in set(existing_idx)]
        if verbose:
            print(f"[{uid}] --force: dropped {len(existing_idx)} existing "
                  f"{TASK_TYPE} row(s) before regenerating")

    bq = BackendQuery(backend_dir=str(backend_dir))
    t_now = 0
    for r in records:
        try:
            t_now = max(t_now, int(r.get("ts") or 0))
        except (TypeError, ValueError):
            pass

    instances = build_personal_qa_hallucination(
        bq, uid, t_now, discovery_llm=discovery_llm, rng_seed=rng_seed,
        verbose=verbose, backend_dir=backend_dir,
    )
    if not instances:
        return {"user_id": uid, "status": "empty", "n_new": 0}

    # Project through the SAME row pipeline a full prepare run uses, then
    # render the projected rows into test.json record shape via
    # dump_test_samples_json (written to a temp path so the real test.json
    # is only touched by the atomic merge below).
    seq0 = len(records)
    projected = [
        _prep._project_row(seq0 + i, TASK_TYPE, inst, uid, int(inst["t_test"]))
        for i, inst in enumerate(instances)
    ]
    fd, tmp_records_path = tempfile.mkstemp(
        prefix=f"pqa_records_{uid}.", suffix=".json")
    os.close(fd)
    try:
        dump_test_samples_json(
            uid, output_path=tmp_records_path,
            backend_dir=str(backend_dir), precomputed_rows=projected,
        )
        new_records = json.loads(Path(tmp_records_path).read_text(encoding="utf-8"))
    finally:
        try:
            os.unlink(tmp_records_path)
        except OSError:
            pass

    merged = records + list(new_records)
    # Keep the file ts-sorted like a fresh build (stable sort: existing
    # relative order is preserved on ties). Row contents are untouched;
    # resume / replay key on query_id, not file position.
    merged.sort(key=lambda r: int(r.get("ts") or 0) if isinstance(r, dict) else 0)
    _atomic_write_json(test_path, merged)

    return {"user_id": uid, "status": "ok", "n_new": len(new_records),
            "n_total": len(merged),
            "domains": [
                ((inst.get("groundtruth_preference") or {}).get("fact_domain"))
                for inst in instances
            ]}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    grp = ap.add_mutually_exclusive_group(required=True)
    grp.add_argument("--user_id", help="Single user id, e.g. 115")
    grp.add_argument("--all", action="store_true",
                     help="Every backend/*/test.json persona")
    ap.add_argument("--backend_dir", default="backend")
    ap.add_argument("--rng_seed", type=int, default=0)
    ap.add_argument("--force", action="store_true",
                    help="Regenerate even when rows already exist (drops them first)")
    ap.add_argument("--dry_run", action="store_true",
                    help="Corpus scan + domain absence report only — no LLM calls, "
                         "no file writes")
    args = ap.parse_args()

    backend_dir = Path(args.backend_dir)
    uids = [args.user_id] if args.user_id else _users_with_test_json(backend_dir)
    if not uids:
        print("no users resolved", file=sys.stderr)
        return 2

    if args.dry_run:
        for uid in uids:
            rep = _dry_run_one(backend_dir, uid)
            print(f"[{uid}] events={rep['n_events']}  "
                  f"absent_domains={len(rep['absent_domains'])} "
                  f"{rep['absent_domains']}")
            for k, hits in rep["disqualified"].items():
                print(f"        disqualified {k}: corpus hits {hits}")
        return 0

    import prepare_eval_data as _prep
    discovery = _prep._build_llm_client()
    if discovery is None:
        print("discovery LLM client unavailable — cannot generate; check API "
              "credentials (.env)", file=sys.stderr)
        return 2

    reports = []
    for uid in uids:
        try:
            reports.append(_append_one(
                backend_dir, uid, discovery, args.rng_seed, args.force,
            ))
        except Exception as exc:
            reports.append({"user_id": uid, "status": "error",
                            "error": f"{type(exc).__name__}: {exc}"})
        r = reports[-1]
        print(f"[{r['user_id']}] {r['status']}"
              + (f"  +{r['n_new']} rows (total {r['n_total']}) "
                 f"domains={r['domains']}" if r.get("status") == "ok" else
                 f"  {r.get('error', '')}" if r.get("status") == "error" else ""))

    ok = sum(1 for r in reports if r["status"] == "ok")
    n_new = sum(r.get("n_new", 0) for r in reports)
    print(f"\n=== add_personal_qa_hallucination summary ===")
    print(f"  ok={ok}  skipped_exists="
          f"{sum(1 for r in reports if r['status'] == 'skipped_exists')}  "
          f"empty={sum(1 for r in reports if r['status'] == 'empty')}  "
          f"error={sum(1 for r in reports if r['status'] == 'error')}  "
          f"new_rows={n_new}")
    print("NOTE: persona.html not regenerated — new test cards render on the "
          "next full prepare_eval_data run.")
    return 0 if all(r["status"] in ("ok", "skipped_exists", "empty")
                    for r in reports) else 1


if __name__ == "__main__":
    sys.exit(main())
